version: '3'

services:
    nginx:
        image: nginx:1.20.1-alpine
        container_name: "vote_nginx"
        volumes:
          - ./docker/nginx/conf/app.conf:/etc/nginx/conf.d/app.conf
        ports:
          - 80:80
        depends_on:
          - app
          - db
        restart: always

    app:
        container_name: 'vote_app'
        build:
            context: .
            dockerfile: docker/go/Dockerfile
        volumes:
            - ./:/go/src
        ports:
            - "3000:3000"
        tty: true
        command: air
        environment:
            DB_NAME: "vote"
            DB_HOST: "db"
            DB_USER: "root"
            DB_PASSWORD: "mysql"

    db:
        container_name: 'vote_db'
        build:
            context: .
            dockerfile: docker/mysql/Dockerfile
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "mysql"
            TZ: "Asia/Tokyo"
        ports:
            - 3306:3306
        volumes:
            - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
            - vote-db-store:/var/lib/mysql

volumes:
    vote-db-store:
